# -*- coding: utf-8 -*-
"""Calcular Média

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qgk-f5yWSPclZnwKebarJvLWAr1X4f0o
"""

print("Seja bem-vindo(a) ao sistema de cálculo de médias da Escola Deep Learning!")
nota1 = float(input("Por favor, digite a primeira nota: "))
nota2 = float(input("Agora, digite a segunda nota: "))

media = (nota1+nota2)/2

print("Média: ",media)